# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


images = [
	'https://sashajuliard.com/sashanew/wp-content/uploads/2010/12/Sasha-Juliard-Portfolio-1-5.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2010/12/Sasha-Juliard-Portfolio-3-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2010/12/Sasha-Juliard-Portfolio-2-4.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2010/12/Sasha-Juliard-Portfolio-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2010/12/Sasha-Juliard-Portfolio-6.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2011/12/Sasha-Juliard-Portfolio-11.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2011/12/Sasha-Juliard-Portfolio-33.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2011/12/Sasha-Juliard-Portfolio-35.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2011/12/Sasha-Juliard-Portfolio-36.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2011/12/Sasha-Juliard-Portfolio-38.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2011/12/Sasha-Juliard-Portfolio-40.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2011/12/Sasha-Juliard-Portfolio-6-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2011/12/Sasha-Juliard-Portfolio-7-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2012/06/Sasha-Juliard-Portfolio-5-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2013/01/Sasha-Juliard-Portfolio-1-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2013/01/Sasha-Juliard-Portfolio-1-21.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2013/01/Sasha-Juliard-Portfolio-12-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2013/01/Sasha-Juliard-Portfolio-12-31.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2013/01/Sasha-Juliard-Portfolio-2-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2013/01/Sasha-Juliard-Portfolio-2-21.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2013/01/Sasha-Juliard-Portfolio-3-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2013/01/Sasha-Juliard-Portfolio-3-21.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2013/01/Sasha-Juliard-Portfolio-7.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-1-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-1-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-1-21.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-1-22.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-1-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-10.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-101.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-11.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-110.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-111.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-12-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-12.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-121.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-122.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-13-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-13.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-131.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-132.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-14.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-15.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-16-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-16.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-161.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-17-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-17.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-18.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-181.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-19.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-191.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-20-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-20.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-201.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-21.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-211.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-22.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-23-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-23.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-24-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-24.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-27.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-28.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-3-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-31.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-4-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-4.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-41.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-42.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-43.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-5-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-5-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-5-31.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-5.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-51.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-54.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-57.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-6-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-6-4.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-6-41.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-6.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-61.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-7-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-7-21.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-7.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-8.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-9.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/10/Sasha-Juliard-Portfolio-91.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-10.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-101.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-11.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-12.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-13.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-14.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-4.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-41.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-5.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-6.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-7.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-8.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2014/12/Sasha-Juliard-Portfolio-9.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-10-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-10.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-11.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-12.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-13-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-13.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-14-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-14.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-15.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-16.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-17.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-18.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-19.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-20.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-21-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-21-2-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-21-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-21.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-22.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-24.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-25.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-26.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-27.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-29.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-3-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-30.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-31.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-36.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-4-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-4.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-42.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-43.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-46-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-46.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-5-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-5.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-6-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-6-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-6.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-7-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-7-2-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-7-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-7.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-8-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-8-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-8.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-9-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-9-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2015/09/Sasha-Juliard-Yoga-Portfolio-9.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-10.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-11.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-12.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-15.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-16.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-17.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-18.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-19.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-20.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-21.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-22.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-23.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-24.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-25.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-26.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-27.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-28.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-33.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-34.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-36.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-37.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-4-4.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-4.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-5-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-5.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-7.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-8.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Adventure-Portfolio-9.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-1-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-1-5.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-1-6.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-10-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-11-2-1-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-11-2-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-11-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-12-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-13-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-13.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-14-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-15.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-16.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-17-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-17.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-18-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-18.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-19.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-2-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-20-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-20.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-3-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-4-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-4-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-4.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-5-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-5-2-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-5-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-5.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-6-2-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-6-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-6-4.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-7-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-8-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Portfolio-9-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-10.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-11.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-12.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-13.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-14.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-15.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-16-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-16.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-17.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-18.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-19.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-2-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-2-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-20.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-21.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-22.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-23-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-23.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-24-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-24.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-25.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-26.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-27.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-28-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-28.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-29.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-3-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-3.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-30.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-31.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-32-1.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-32.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-33.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-35.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-4-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-4.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-5.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-6-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-6.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-7.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-8.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-9-2.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/03/Sasha-Juliard-Retreats-Portfolio-9.jpg',
	'https://sashajuliard.com/sashanew/wp-content/uploads/2016/06/Sasha-Juliard-people-portfolio-3.jpg'
]




i=1

images.each do |image_url|
	Post.find_or_create_by( name: "My Great Picture", description: "Knausgaard chia pok pok cardigan hammock. Skateboard church-key shoreditch williamsburg, pork belly iceland vexillologist man bun chia kale chips cronut direct trade meh biodiesel four loko. Before they sold out squid mumblecore, tilde raclette pitchfork man braid.", url: image_url, user_id: rand(4))


  	n=0
	while n < 5 do
		Comment.find_or_create_by(content: "Trust fund quinoa lyft everyday carry man bun slow-carb lumbersexual fam squid. Cray hammock cred put a bird on it.", post_id: i, user_id: rand(4))

		Comment.find_or_create_by(content: "Trust fund quinoa lyft everyday carry man bun slow-carb lumbersexual fam squid. Cray hammock cred put a bird on it.", post_id: (i+33), user_id: rand(4))
		n+=1
	end
	i+= 1
end


i=0

while i < 50 do
	Post.find_or_create_by( name: "Bear - #{i}", description: "Knausgaard chia pok pok cardigan hammock. Skateboard church-key shoreditch williamsburg, pork belly iceland vexillologist man bun chia kale chips cronut direct trade meh biodiesel four loko. Before they sold out squid mumblecore, tilde raclette pitchfork man braid.", url: "https://www.placebear.com/#{rand(25..85)*10}/#{rand(25..85)*10}", user_id: 3)
  	n=0
	while n < 5 do
		Comment.find_or_create_by(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempor vel arcu vitae varius. Donec eu ornare quam, nec ultricies magna. In dignissim ligula leo, at pellentesque massa efficitur at.", post_id: i, user_id: rand(4))
		n+=1
	end
	i+= 1
end

i=0

while i < 50 do
	Post.find_or_create_by( name: "Bacon - #{i}", description: "Knausgaard chia pok pok cardigan hammock. Skateboard church-key shoreditch williamsburg, pork belly iceland vexillologist man bun chia kale chips cronut direct trade meh biodiesel four loko. Before they sold out squid mumblecore, tilde raclette pitchfork man braid.", url: "https://www.baconmockup.com/#{rand(25..85)*10}/#{rand(25..85)*10}", user_id: 4)
  	n=0
	while n < 5 do
		Comment.find_or_create_by(content: "Donec tincidunt tincidunt egestas. Donec sit amet luctus nulla. Phasellus id erat quis enim gravida molestie. Phasellus semper mi ex, non congue felis consequat vel. Integer volutpat metus id commodo gravida.", post_id: i, user_id: rand(4))
		n+=1
	end
	i+= 1
end
